/* 
**  mod_sendfile_handler.c -- Apache sample sendfile_handler module
**  [Autogenerated via ``apxs -n sendfile_handler -g'']
**
**  To play with this sample module, first compile it into a
**  DSO file and install it into Apache's libexec directory 
**  by running:
**
**    $ apxs -c -i mod_sendfile_handler.c
**
**  Then activate it in Apache's httpd.conf file, for instance
**  for the URL /sendfile_handler, as follows:
**
**    #   httpd.conf
**    LoadModule sendfile_handler_module libexec/mod_sendfile_handler.so
**    <Location /sendfile_handler>
**    SetHandler sendfile_handler
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /%NAME and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/sendfile_handler 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_sendfile_handler.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"


const char ETC_SERVICES[] = "/etc/services";

/* The sample content handler */
static int sendfile_handler_handler(request_rec *r)
{
  FILE *file;

  file = ap_pfopen(r->pool, ETC_SERVICES, "r");
  if(file == NULL){
/*    ap_log_rerror(APLOG_MARK, APLOG_ERR, r,
        "file permissions deny server access: %s",
        ETC_SERVICES);
        */
    return HTTP_FORBIDDEN;
  }

  r->content_type = "text/plain";      

  ap_send_http_header(r);
  if (r->header_only){
    return OK;
  }

  ap_send_fd(file, r);
  ap_pfclose(r->pool, file);
  return OK;
}

/* Dispatch list of content handlers */
static const handler_rec sendfile_handler_handlers[] = { 
    { "sendfile_handler", sendfile_handler_handler }, 
    { NULL, NULL }
};

/* Dispatch list for API hooks */
module MODULE_VAR_EXPORT sendfile_handler_module = {
    STANDARD_MODULE_STUFF, 
    NULL,                  /* module initializer                  */
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    sendfile_handler_handlers,       /* [#8] MIME-typed-dispatched handlers */
    NULL,                  /* [#1] URI to filename translation    */
    NULL,                  /* [#4] validate user id from request  */
    NULL,                  /* [#5] check if the user is ok _here_ */
    NULL,                  /* [#3] check access by host address   */
    NULL,                  /* [#6] determine MIME type            */
    NULL,                  /* [#7] pre-run fixups                 */
    NULL,                  /* [#9] log a transaction              */
    NULL,                  /* [#2] header parser                  */
    NULL,                  /* child_init                          */
    NULL,                  /* child_exit                          */
    NULL                   /* [#0] post read-request              */
};

